/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionprog;

import static gestionprog.Produitf.jTable1;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bani
 */
public class Addproduit extends javax.swing.JFrame {
           GestionProd prod=new GestionProd();


    /**
     * Creates new form Addproduit
     */
    public Addproduit() {
        initComponents();
         ImageIcon icon;
        icon=new ImageIcon("src/gestionprog/image/iconapl.png");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idref = new javax.swing.JLabel();
        idref1 = new javax.swing.JLabel();
        idref2 = new javax.swing.JLabel();
        idref3 = new javax.swing.JLabel();
        idref4 = new javax.swing.JLabel();
        idtxtref1 = new javax.swing.JTextField();
        idtxtnom1 = new javax.swing.JTextField();
        idtxtqtt1 = new javax.swing.JTextField();
        idtxtqtr1 = new javax.swing.JTextField();
        idtxtprix1 = new javax.swing.JTextField();
        addprod = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajouter Un Produit");
        setBackground(new java.awt.Color(0, 204, 255));
        setIconImages(null);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Ajouter Un Produit");

        idref.setText("Ref                     :");

        idref1.setText("Nom de produit  :");

        idref2.setText("Quantité Total     :");

        idref3.setText("Prix                     :");

        idref4.setText("Quantité Restant :");

        idtxtref1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtref1ActionPerformed(evt);
            }
        });

        idtxtnom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtnom1ActionPerformed(evt);
            }
        });

        idtxtqtt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtqtt1ActionPerformed(evt);
            }
        });
        idtxtqtt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idtxtqtt1KeyTyped(evt);
            }
        });

        idtxtqtr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtqtr1ActionPerformed(evt);
            }
        });
        idtxtqtr1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idtxtqtr1KeyTyped(evt);
            }
        });

        idtxtprix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtprix1ActionPerformed(evt);
            }
        });
        idtxtprix1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idtxtprix1KeyTyped(evt);
            }
        });

        addprod.setBackground(new java.awt.Color(153, 255, 153));
        addprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionprog/image/add32.png"))); // NOI18N
        addprod.setText("Add");
        addprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addprodActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idref4)
                    .addComponent(idref3)
                    .addComponent(idref1)
                    .addComponent(idref)
                    .addComponent(idref2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idtxtnom1)
                    .addComponent(idtxtref1)
                    .addComponent(idtxtqtt1)
                    .addComponent(idtxtqtr1)
                    .addComponent(idtxtprix1))
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(addprod, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idref, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxtref1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idref1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxtnom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idref2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxtqtt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idref4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxtqtr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idref3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxtprix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addprod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idtxtref1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtref1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtref1ActionPerformed

    private void idtxtnom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtnom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtnom1ActionPerformed

    private void idtxtqtt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtqtt1ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_idtxtqtt1ActionPerformed

    private void idtxtqtr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtqtr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtqtr1ActionPerformed

    private void idtxtprix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtprix1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtprix1ActionPerformed
     public boolean veriftext()
            
      {
          if(idtxtref1.getText().equals("")||idtxtqtt1.getText().equals("")
                  ||idtxtqtr1.getText().equals("")||
                  idtxtprix1.getText().equals(""))
          {
              JOptionPane.showMessageDialog(null, "Un ou plusieurs champs vides");
          return false;
          }
          else
                    {
                      return true;
                    }
    
      }
    private void addprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addprodActionPerformed
        // TODO add your handling code here:
        String name=idtxtnom1.getText();
        String ref=idtxtref1.getText();
        String qlttotale=idtxtqtt1.getText();
        String qltrestant=idtxtqtr1.getText();
        String prix=idtxtprix1.getText();
        GestionProd produit= new GestionProd();
        if(veriftext())
        {
        produit.insertUpdateDeletProduit('i', null,name,ref,  qlttotale, qltrestant, prix);
        //add direct in jtable in last row
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Ref","Nom","Quantite totale","Quantite Rest","Prix"}));
        //add direct in jtable
        prod.fillProduitJtable(jTable1, "");
        this.dispose();
        }

    }//GEN-LAST:event_addprodActionPerformed

    private void idtxtqtt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtqtt1KeyTyped
        // TODO add your handling code here:
            if(!Character.isDigit(evt.getKeyChar()))
              {
                evt.consume();
              }
    }//GEN-LAST:event_idtxtqtt1KeyTyped

    private void idtxtqtr1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtqtr1KeyTyped
        // TODO add your handling code here:
            if(!Character.isDigit(evt.getKeyChar()))
              {
                evt.consume();
              }
    }//GEN-LAST:event_idtxtqtr1KeyTyped

    private void idtxtprix1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtprix1KeyTyped
        // TODO add your handling code here:
            if(!Character.isDigit(evt.getKeyChar()))
              {
                evt.consume();
              }
    }//GEN-LAST:event_idtxtprix1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addproduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addproduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addproduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addproduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new Addproduit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addprod;
    private javax.swing.JLabel idref;
    private javax.swing.JLabel idref1;
    private javax.swing.JLabel idref2;
    private javax.swing.JLabel idref3;
    private javax.swing.JLabel idref4;
    private javax.swing.JTextField idtxtnom1;
    private javax.swing.JTextField idtxtprix1;
    private javax.swing.JTextField idtxtqtr1;
    private javax.swing.JTextField idtxtqtt1;
    private javax.swing.JTextField idtxtref1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
