/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionprog;

import java.awt.Color;
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bani
 */
public class Produitf extends javax.swing.JFrame {

    /**
     * Creates new form Produitf
     */
       GestionProd prod=new GestionProd();

    public Produitf() {
        initComponents();
        //afiiche touut les produit
        prod.fillProduitJtable(jTable1, "");
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.BLACK);
        jTable1.setSelectionBackground(Color.BLUE);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idnom = new javax.swing.JLabel();
        idref = new javax.swing.JLabel();
        idqnt = new javax.swing.JLabel();
        idprix = new javax.swing.JLabel();
        idqnr = new javax.swing.JLabel();
        idtxtref = new javax.swing.JTextField();
        idtxtnom = new javax.swing.JTextField();
        idtxtqtt = new javax.swing.JTextField();
        idtxtqtr = new javax.swing.JTextField();
        idtxtprix = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        idref1 = new javax.swing.JLabel();
        idtxtrecherche = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addprod = new javax.swing.JButton();
        idtxt = new javax.swing.JTextField();
        idref2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idnom.setText("Nom de Produit   :");

        idref.setText("Ref                     :");

        idqnt.setText("Qunatité Totale   :");

        idprix.setText("Prix                      :");

        idqnr.setText("Qunatité Restant :");

        idtxtref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtrefActionPerformed(evt);
            }
        });

        idtxtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtnomActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ref", "Nom", "Quantite totale", "Quantite Rest", "Prix "
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        idref1.setText("Recherche   :");

        idtxtrecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtrechercheActionPerformed(evt);
            }
        });
        idtxtrecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idtxtrechercheKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idtxtrechercheKeyReleased(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        addprod.setBackground(new java.awt.Color(153, 255, 153));
        addprod.setText("Add");
        addprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addprodActionPerformed(evt);
            }
        });

        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });

        idref2.setText("Id                     :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idqnt)
                                    .addComponent(idref)
                                    .addComponent(idnom)
                                    .addComponent(idref2))
                                .addComponent(idqnr))
                            .addComponent(idprix))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idtxtprix, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxtref, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxtqtt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxtqtr, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addprod, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(idref1)
                        .addGap(18, 18, 18)
                        .addComponent(idtxtrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idref2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idref, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxtref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idref1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtxtrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idnom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idqnt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxtqtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idqnr, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxtqtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idprix, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxtprix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addprod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idtxtrechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtrechercheActionPerformed
        // TODO add your handling code here:
        GestionProd prod= new GestionProd();
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Ref","Nom","Quantite totale","Quantite Rest","Prix"}));
        prod.fillProduitJtable(jTable1, idtxtrecherche.getText());
    }//GEN-LAST:event_idtxtrechercheActionPerformed

    private void addprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addprodActionPerformed
        // TODO add your handling code here:
        String name=idtxtnom.getText();
        String ref=idtxtref.getText();
        String qlttotale=idtxtqtt.getText();
        String qltrestant=idtxtqtr.getText();
        String prix=idtxtprix.getText();
        GestionProd produit= new GestionProd();
        if(name.equals(""))
            { JOptionPane.showMessageDialog(null, "name vide");
            }
        else{
        produit.insertUpdateDeletProduit('i', null, name, ref, qlttotale, qltrestant, prix);
        //add direct in jtable in last row
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Ref","Nom","Quantite totale","Quantite Rest","Prix"}));
        //add direct in jtable
        prod.fillProduitJtable(jTable1, "");
        }
        
    }//GEN-LAST:event_addprodActionPerformed

    private void idtxtrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtrefActionPerformed

    private void idtxtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtnomActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int rowIndex=jTable1.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        idtxt.setText(model.getValueAt(rowIndex, 0).toString());
        idtxtnom.setText(model.getValueAt(rowIndex, 2).toString());
        idtxtref.setText(model.getValueAt(rowIndex, 1).toString());
        idtxtqtt.setText(model.getValueAt(rowIndex, 3).toString());
        idtxtqtr.setText(model.getValueAt(rowIndex, 4).toString());
        idtxtprix.setText(model.getValueAt(rowIndex, 5).toString());
         jTable1.isEditing() ;
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void idtxtrechercheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtrechercheKeyPressed
        // TODO add your handling code here:
        GestionProd prod= new GestionProd();
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Ref","Nom","Quantite totale","Quantite Rest","Prix"}));
        prod.fillProduitJtable(jTable1, idtxtrecherche.getText());
    }//GEN-LAST:event_idtxtrechercheKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        String name=idtxtnom.getText();
        String ref=idtxtref.getText();
        String qlttotale=idtxtqtt.getText();
        String qltrestant=idtxtqtr.getText();
        String prix=idtxtprix.getText();
        int id =Integer.valueOf(idtxt.getText());
        GestionProd produit= new GestionProd();
        if(name.equals(""))
            { JOptionPane.showMessageDialog(null, "name vide");
            }
        else{
        produit.insertUpdateDeletProduit('u', id, name, ref, qlttotale, qltrestant, prix);
                jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Ref","Nom","Quantite totale","Quantite Rest","Prix"}));

                prod.fillProduitJtable(jTable1, idtxtrecherche.getText());

        

        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String name=idtxtnom.getText();
        int id =Integer.valueOf(idtxt.getText());
        GestionProd produit= new GestionProd();
        if(name.equals(""))
            { JOptionPane.showMessageDialog(null, "name vide");
            }
        else{
        produit.insertUpdateDeletProduit('d', id, null, null, null, null, null);
       prod.fillProduitJtable(jTable1, "");
       jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Ref","Nom","Quantite totale","Quantite Rest","Prix"}));
               prod.fillProduitJtable(jTable1, idtxtrecherche.getText());



         //add direct in jtable
        

        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void idtxtrechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtrechercheKeyReleased
        // TODO add your handling code here:
        GestionProd prod= new GestionProd();
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Ref","Nom","Quantite totale","Quantite Rest","Prix"}));
        prod.fillProduitJtable(jTable1, idtxtrecherche.getText());
    }//GEN-LAST:event_idtxtrechercheKeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produitf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produitf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produitf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produitf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produitf().setVisible(true);
            }
        });
        
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addprod;
    private javax.swing.JLabel idnom;
    private javax.swing.JLabel idprix;
    private javax.swing.JLabel idqnr;
    private javax.swing.JLabel idqnt;
    private javax.swing.JLabel idref;
    private javax.swing.JLabel idref1;
    private javax.swing.JLabel idref2;
    private javax.swing.JTextField idtxt;
    private javax.swing.JTextField idtxtnom;
    private javax.swing.JTextField idtxtprix;
    private javax.swing.JTextField idtxtqtr;
    private javax.swing.JTextField idtxtqtt;
    private javax.swing.JTextField idtxtrecherche;
    private javax.swing.JTextField idtxtref;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
