/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionprog;

import javax.swing.ImageIcon;

/**
 *
 * @author Bani
 */
public class Statistique extends javax.swing.JFrame {

    /**
     * Creates new form Option
     */
    public Statistique() {
        initComponents();
        ImageIcon icon;
        icon=new ImageIcon("src/gestionprog/image/iconapl.png");
        setIconImage(icon.getImage());
         GestionProd prod=new GestionProd();
         
        idtxtsumqt.setText(Integer.toString(prod.sumQuantit()));
        idtxttota1prod.setText(Integer.toString(prod.totalproduit()));
        idtxttotalprix.setText(Integer.toString(prod.totalprix())+" DT");

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idtxtsumqt = new javax.swing.JTextField();
        idtxttota1prod = new javax.swing.JTextField();
        idtxttotalprix = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Globale");
        setBackground(new java.awt.Color(0, 204, 255));
        setResizable(false);

        idtxtsumqt.setEditable(false);
        idtxtsumqt.setBackground(new java.awt.Color(204, 204, 255));
        idtxtsumqt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        idtxtsumqt.setCaretColor(new java.awt.Color(255, 51, 51));
        idtxtsumqt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtsumqtActionPerformed(evt);
            }
        });
        idtxtsumqt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idtxtsumqtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idtxtsumqtKeyReleased(evt);
            }
        });

        idtxttota1prod.setEditable(false);
        idtxttota1prod.setBackground(new java.awt.Color(204, 204, 255));
        idtxttota1prod.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        idtxttota1prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxttota1prodActionPerformed(evt);
            }
        });

        idtxttotalprix.setEditable(false);
        idtxttotalprix.setBackground(new java.awt.Color(204, 204, 255));
        idtxttotalprix.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        idtxttotalprix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxttotalprixActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Numbre de prodiuts :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Quantité Stocké       :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("prix total                  :");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Gestion Globale");

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idtxtsumqt)
                            .addComponent(idtxttota1prod)
                            .addComponent(idtxttotalprix, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtxtsumqt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtxttota1prod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idtxttotalprix, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idtxtsumqtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtsumqtActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_idtxtsumqtActionPerformed

    private void idtxttota1prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxttota1prodActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_idtxttota1prodActionPerformed

    private void idtxttotalprixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxttotalprixActionPerformed
        // TODO add your handling code here:
                   
    }//GEN-LAST:event_idtxttotalprixActionPerformed

    private void idtxtsumqtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtsumqtKeyPressed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_idtxtsumqtKeyPressed

    private void idtxtsumqtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtsumqtKeyReleased
        // TODO add your handling code here:
    
    }//GEN-LAST:event_idtxtsumqtKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField idtxtsumqt;
    private javax.swing.JTextField idtxttota1prod;
    private javax.swing.JTextField idtxttotalprix;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
